FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS build

WORKDIR /workspace
COPY gradle/ gradle/
COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY src/ src/

RUN ./gradlew quarkusBuild \
    -Dquarkus.native.enabled=true \
    -Dquarkus.package.jar.enabled=false \
    -Dquarkus.native.container-build=false

FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /work/
COPY --from=build /workspace/build/tally-0.1.0-runner /work/application

USER 1001
EXPOSE 8080
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
